/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GachaRouteImport } from './routes/gacha'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GachaRoute = GachaRouteImport.update({
  id: '/gacha',
  path: '/gacha',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gacha': typeof GachaRoute
  '/mcp': typeof McpRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gacha': typeof GachaRoute
  '/mcp': typeof McpRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gacha': typeof GachaRoute
  '/mcp': typeof McpRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gacha'
    | '/mcp'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gacha'
    | '/mcp'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gacha'
    | '/mcp'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GachaRoute: typeof GachaRoute
  McpRoute: typeof McpRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gacha': {
      id: '/gacha'
      path: '/gacha'
      fullPath: '/gacha'
      preLoaderRoute: typeof GachaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GachaRoute: GachaRoute,
  McpRoute: McpRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
